- rule: Detect Malicious Scripts
  desc: Detect potentially malicious script execution
  condition: >
    evt.type = execve and
    (proc.name in (sh, bash, dash, ash, zsh, ksh, python, perl, ruby) and
    (proc.cmdline contains "curl" or proc.cmdline contains "wget" or proc.cmdline contains "nc" or proc.cmdline contains "netcat" or proc.cmdline contains "python -m SimpleHTTPServer"))
  output: "Potential malicious script detected (command=%proc.cmdline user=%user.name container=%container.info)"
  priority: CRITICAL
  tags: [script, container, security]

- rule: Detect Container Escape Attempt
  desc: Detect processes attempting to access sensitive files on the host from a container
  condition: >
    container.id != host and
    (fd.name in (/etc/shadow, /etc/passwd, /root/.ssh/authorized_keys, /etc/hostname) or
    (proc.name in (nsenter, lxc-attach, runc) and proc.cmdline contains "host"))
  output: "Container escape attempt detected (process=%proc.name user=%user.name file=%fd.name container=%container.info)"
  priority: CRITICAL
  tags: [container, escape, host]

- rule: Detect Malware Activity
  desc: Detect suspicious activities indicative of malware
  condition: >
    proc.name in (cryptominer, botnet, keylogger) or
    (evt.type = open and fd.name contains "/tmp/malicious" and fd.typechar = "f") or
    (evt.type = connect and fd.sip in (known_malicious_ips))
  output: "Suspicious activity detected (process=%proc.name file=%fd.name container=%container.info)"
  priority: CRITICAL
  tags: [malware, security, container]
