stages:
  - initialize
  - static security scan
  - dynamic security scan
  - static security scan report process
  - static security scan report combine
  - sbom scan
  - sbom report process
  - sbom report combine
  - dockle scan
  - dockle report process
  - dockle report combine
  - final combine

include:
  - local: 'ci/initialize.yml'
  - local: 'ci/static security scan/static_security_scan.yml'
  - local: 'ci/static security scan/static_security_report_process.yml'
  - local: 'ci/static security scan/static_security_report_combine.yml'
  - local: 'ci/dynamic security scan/dynamic_security_scan.yml'
  - local: 'ci/sbom scan/sbom_scan.yml'
  - local: 'ci/sbom scan/sbom_report_process.yml'
  - local: 'ci/image linter/dockle_scan.yml'
  - local: 'ci/final_combine.yml'
