[[runners]]
name = "Docker Runner"
url = "http://gitlab-web/"
token = "glrt-QMaHzrDpMA7McdNFrNxi"
executor = "docker"
clone_url = "http://gitlab-web/"
[runners.docker]
tls_verify = false
image = "docker:26.1.2"
privileged = true
disable_entrypoint_overwrite = false
oom_kill_disable = false
disable_cache = false
#volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
volumes = ["/cache"]
network_mode = "gitlab-network"
shm_size = 0
[runners.cache]
[runners.cache.s3]
[runners.cache.gcs]
